import '../styles/globals.css';
import MainAppWrapper from "../components/MainAppWrapper";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
  themeColor: "#fb42b2"
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ background: '#222', color: '#fff' }}>
        <MainAppWrapper>
          {children}
        </MainAppWrapper>
      </body>
    </html>
  )
}
