/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:a52e9e7b-e0d4-49bc-a4d9-4e04d2cd1239",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_RfmMfQp0K",
    "aws_user_pools_web_client_id": "5neqfkmnd5pm3jm0lcm0bvp2g6",
    "oauth": {},
    "aws_user_files_s3_bucket": "amplifyphotobook08a7c938b98a4b1f92a2c88e1ef6f90181446-dev",
    "aws_user_files_s3_bucket_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://nktvocnqrfh4zdouhnv7h2jqc4.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-fakeApiId123456"
};


export default awsmobile;
